<?php

namespace CCDI\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{

    public function findByAnniversary(\DateTime $day) {

        $emConfig = $this->getEntityManager()->getConfiguration();
        $emConfig->addCustomDatetimeFunction('MONTH', 'CCDI\CoreBundle\Doctrine\Extensions\Month');
        $emConfig->addCustomDatetimeFunction('DAY', 'CCDI\CoreBundle\Doctrine\Extensions\Day');

        return $this->getEntityManager()->createQueryBuilder()
            ->select('e')
            ->from('CCDICoreBundle:Employee', 'e')
            ->where('MONTH(e.birthday) = ' . $day->format('m'))
            ->andWhere('DAY(e.birthday) = ' . $day->format('d'))
            ->orderBy('e.name', 'DESC');
    }

    public function getByAnniversary(\DateTime $day) {
        return $this->findByAnniversary($day)->getQuery()->execute();
    }

}