<?php

namespace CCDI\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{

    public function findByBirthday(\DateTime $day) {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('e')
            ->from('CCDICoreBundle:Employee', 'e')
            ->where('e.birthday = ' . $day->format('Y-m-d'))
            ->orderBy('e.name', 'DESC');
    }

    public function getByBirthday(\DateTime $day) {
        return $this->findByBirthday($day)->getQuery()->execute();
    }

}