#
# more information can be found here http://sonata-project.org/bundles/page
#
cmf_routing:
    chain:
        routers_by_id:
            # enable the DynamicRouter with high priority to allow overwriting configured routes with content
            #symfony_cmf_routing_extra.dynamic_router: 200
            # enable the symfony default router with a lower priority
            sonata.page.router: 150
            router.default: 100

sonata_page:
    multisite:             host
    use_streamed_response: false # set the value to false in debug mode or if the reverse proxy does not handle streamed response

    ignore_uri_patterns:
        - ^/admin(.*)
        - ^/api/(.*)
        - ^/tv/(.*)

    ignore_route_patterns:
        - (.*)admin(.*)     # ignore admin route, ie route containing 'admin'
        - ^_(.*)            # ignore symfony routes

    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc

    cache_invalidation:
        service:  sonata.page.cache.invalidation.simple
        recorder: sonata.page.cache.recorder
        classes:
            "Application\Sonata\PageBundle\Entity\Block": getId

    assets:
        stylesheets:
            - assetic/sonata_front_css.css

        javascripts:
            - assetic/sonata_front_js.js

    default_template: fullscreen
    templates:
        fullscreen:
            path: 'CCDITVBundle::Fullscreen.html.twig'
            name: 'Fullscreen'
            containers:
                 content: 
                     name: Conteúdo
            matrix:
                 layout: |
                     CCCCCCCC
                 mapping:
                     C: content
        2columns:
            path: 'CCDITVBundle::2Columns.html.twig'
            name: '2 Colunas'
            containers:
                 left_col:
                     name: Coluna esquerda
                 right_col:
                     name: Coluna direita
            matrix:
                 layout: |
                     LLLLRRRR
                 mapping:
                     L: left_col
                     R: right_col
        header2columns:
            path: 'CCDITVBundle::Header-2Columns.html.twig'
            name: 'Cabeçalho + 2 colunas'
            containers:
                 header:
                     name: Cabeçalho
                 left_col:
                     name: Coluna esquerda
                 right_col:
                     name: Coluna direita
            matrix:
                 layout: |
                     HHHHHHHH
                     LLLLRRRR
                 mapping:
                     H: header
                     L: left_col
                     R: right_col
        header2columnsfooter:
            path: 'CCDITVBundle::Header-2Columns-Footer.html.twig'
            name: 'Cabeçalho + 2 colunas + Rodapé'
            containers:
                 header:
                     name: Cabeçalho
                 left_col:
                     name: Coluna esquerda
                 right_col:
                     name: Coluna direita
                 footer:
                     name: Rodapé
            matrix:
                 layout: |
                     HHHHHHHH
                     LLLLRRRR
                     FFFFFFFF
                 mapping:
                     H: header
                     L: left_col
                     R: right_col
                     F: footer
        2columnsfooter:
            path: 'CCDITVBundle::2Columns-Footer.html.twig'
            name: '2 colunas + Rodapé'
            containers:
                 left_col:
                     name: Coluna esquerda
                 right_col:
                     name: Coluna direita
                 footer:
                     name: Rodapé
            matrix:
                 layout: |
                     LLLLRRRR
                     FFFFFFFF
                 mapping:
                     L: left_col
                     R: right_col
                     F: footer
        headercontentfooter:
            path: 'CCDITVBundle::Header-Content-Footer.html.twig'
            name: 'Cabeçalho + Conteúdo + Rodapé'
            containers:
                 header:
                     name: Cabeçalho
                 content:
                     name: Conteúdo
                 footer:
                     name: Rodapé
            matrix:
                 layout: |
                     HHHHHHHH
                     CCCCCCCC
                     FFFFFFFF
                 mapping:
                     H: header
                     C: content
                     F: footer

    page_defaults:
        homepage: { decorate: false, enabled: true }

    caches:
        esi:
            token:    add an unique token here # default is a random value
            version:  3                        # version 3 is the default on debian wheezy ...
            servers:
                # you need to ajust this configuration to match your varnish configuration
                #- %sonata_page.varnish.command%
        ssi:
            token:    add an unique token here # default is a random value

    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error
    
# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataPageBundle: ~
                    SonataPageBundle: ~
