services:
    ccdi.admin.post:
        class: CCDI\AdminBundle\Admin\PostAdmin
        arguments: [~, CCDI\CoreBundle\Entity\Post, CCDIAdminBundle:PostAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Post}

    ccdi.admin.employee:
        class: CCDI\AdminBundle\Admin\EmployeeAdmin
        arguments: [~, CCDI\CoreBundle\Entity\Employee, CCDIAdminBundle:EmployeeAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Employee}
